train:
  _target_: src.datasets.BraTS23CachedVectorDataset
  cache_dir: "data/cached/brats23"
  partition: "train"
  usage_ratio: 1.0
  split_strategy: "three_way"
  val_ratio: 0.1
  test_ratio: 0.1
  fold: 0
  n_folds: 5
  seed: 42
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.BraTS23CachedVectorDataset
  cache_dir: "data/cached/brats23"
  partition: "val"
  usage_ratio: 1.0
  split_strategy: "three_way"
  val_ratio: 0.1
  test_ratio: 0.1
  fold: 0
  n_folds: 5
  seed: 42
  instance_transforms: ${transforms.instance_transforms.inference}

test:
  _target_: src.datasets.BraTS23CachedVectorDataset
  cache_dir: "data/cached/brats23"
  partition: "test"
  usage_ratio: 1.0
  split_strategy: "three_way"
  val_ratio: 0.1
  test_ratio: 0.1
  fold: 0
  n_folds: 5
  seed: 42
  instance_transforms: ${transforms.instance_transforms.inference}
