train:
  _target_: src.datasets.BraTS23Dataset
  data_dir: "/path/to/BraTS23-GLI-TrainingData"
  partition: "train"
  usage_ratio: 1.0
  fold: 0
  n_folds: 5
  seed: 42
  require_label: True
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.BraTS23Dataset
  data_dir: "/path/to/BraTS23-GLI-TrainingData"
  partition: "val"
  usage_ratio: 1.0
  fold: 0
  n_folds: 5
  seed: 42
  require_label: True
  instance_transforms: ${transforms.instance_transforms.inference}

test:
  _target_: src.datasets.BraTS23Dataset
  data_dir: "/path/to/BraTS23-GLI-TrainingData"
  partition: "test"
  usage_ratio: 1.0
  fold: 0
  n_folds: 5
  seed: 42
  require_label: True
  instance_transforms: ${transforms.instance_transforms.inference}
