train:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: monai.transforms.CropForegroundd
      keys: ["image", "label"]
      source_key: "image"
      k_divisible: [96, 96, 96]
      allow_smaller: True
    - _target_: monai.transforms.RandSpatialCropd
      keys: ["image", "label"]
      roi_size: [96, 96, 96]
      random_size: False
    - _target_: monai.transforms.RandFlipd
      keys: ["image", "label"]
      prob: 0.5
      spatial_axis: 0
    - _target_: monai.transforms.RandFlipd
      keys: ["image", "label"]
      prob: 0.5
      spatial_axis: 1
    - _target_: monai.transforms.RandFlipd
      keys: ["image", "label"]
      prob: 0.5
      spatial_axis: 2
    - _target_: monai.transforms.RandScaleIntensityd
      keys: ["image"]
      factors: 0.1
      prob: 1.0
    - _target_: monai.transforms.RandShiftIntensityd
      keys: ["image"]
      offsets: 0.1
      prob: 1.0
    - _target_: monai.transforms.EnsureTyped
      keys: ["image", "label"]

inference:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: monai.transforms.EnsureTyped
      keys: ["image", "label"]
